export const GAME_CATEGORIES = [
  { id: "fps", label: "FPS / 경쟁" },
  { id: "openworld", label: "오픈월드" },
  { id: "aaa", label: "AAA 게임" },
  { id: "game", label: "일반 게임" },
];

export const GAME_OPTIONS = [
  { id: "valorant", label: "발로란트", group: "FPS / 경쟁형", category: "fps" },
  { id: "csgo2", label: "CS2", group: "FPS / 경쟁형", category: "fps" },
  { id: "csgo", label: "CS:GO", group: "FPS / 경쟁형", category: "fps" },
  {
    id: "overwatch2",
    label: "오버워치 2",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  {
    id: "apex",
    label: "에이펙스 레전드",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  {
    id: "rainbow6",
    label: "레인보우 식스 시즈",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  { id: "pubg", label: "배틀그라운드", group: "FPS / 경쟁형", category: "fps" },
  {
    id: "fortnite",
    label: "포트나이트",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  {
    id: "marvel_rivals",
    label: "마블 라이벌즈",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  {
    id: "cod_black_ops6",
    label: "콜 오브 듀티: 블랙 옵스 6",
    group: "FPS / 경쟁형",
    category: "fps",
  },
  {
    id: "cyberpunk2077",
    label: "사이버펑크 2077",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "baldurs_gate3",
    label: "발더스 게이트 3",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "god_of_war_ragnarok",
    label: "갓 오브 워 라그나로크",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "black_myth_wukong",
    label: "검은 신화: 오공",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "resident_evil4",
    label: "바이오하자드 RE:4",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "alan_wake2",
    label: "앨런 웨이크 2",
    group: "AAA / GOTY",
    category: "aaa",
  },
  {
    id: "witcher3",
    label: "더 위쳐 3",
    group: "오픈월드",
    category: "openworld",
  },
  {
    id: "elden_ring",
    label: "엘든 링",
    group: "오픈월드",
    category: "openworld",
  },
  {
    id: "ghost_of_tsushima",
    label: "고스트 오브 쓰시마",
    group: "오픈월드",
    category: "openworld",
  },
  {
    id: "red_dead_redemption2",
    label: "레드 데드 리뎀션 2",
    group: "오픈월드",
    category: "openworld",
  },
  {
    id: "horizon_forbidden_west",
    label: "호라이즌 포비든 웨스트",
    category: "openworld",
  },
  { id: "hogwarts_legacy", label: "호그와트 레거시", category: "openworld" },
  { id: "starfield", label: "스타필드", category: "openworld" },
  {
    id: "dragons_dogma2",
    label: "드래곤즈 도그마 2",
    group: "오픈월드",
    category: "openworld",
  },
  {
    id: "dying_light2",
    label: "다잉 라이트 2",
    group: "오픈월드",
    category: "openworld",
  },
  { id: "genshin_impact", label: "원신", group: "일반 게임", category: "game" },
  {
    id: "wuthering_waves",
    label: "명조: 워더링 웨이브",
    group: "일반 게임",
    category: "game",
  },
  {
    id: "zenless_zone_zero",
    label: "젠레스 존 제로",
    group: "일반 게임",
    category: "game",
  },
  { id: "lostark", label: "로스트아크", group: "일반 게임", category: "game" },
  { id: "wow", label: "WoW", group: "일반 게임", category: "game" },
  {
    id: "ffxiv",
    label: "파이널 판타지 XIV",
    group: "일반 게임",
    category: "game",
  },
  {
    id: "cities_skylines2",
    label: "시티즈 스카이라인 2",
    group: "일반 게임",
    category: "game",
  },
  {
    id: "msfs2024",
    label: "MS 플라이트 시뮬레이터 2024",
    group: "일반 게임",
    category: "game",
  },
  {
    id: "farming_sim",
    label: "파밍 시뮬레이터",
    group: "일반 게임",
    category: "game",
  },
];

export const WORK_PROFILES = {
  video_1080p: {
    name: "FHD 영상 편집",
    group: "영상 편집",
    w: { gpu: 0.22, cpu: 0.42, ram: 0.22, storage: 0.14 },
    req: { gpu: 35, cpu: 45, ramGb: 16, storageTb: 1 },
  },
  video_4k: {
    name: "4K 영상 편집",
    group: "영상 편집",
    w: { gpu: 0.32, cpu: 0.34, ram: 0.24, storage: 0.1 },
    req: { gpu: 58, cpu: 64, ramGb: 32, storageTb: 2 },
  },
  video_8k: {
    name: "8K/RAW 영상 편집",
    group: "영상 편집",
    w: { gpu: 0.36, cpu: 0.34, ram: 0.24, storage: 0.06 },
    req: { gpu: 78, cpu: 82, ramGb: 64, storageTb: 2 },
  },
  motion_graphics: {
    name: "모션그래픽/After Effects",
    group: "영상 편집",
    w: { gpu: 0.28, cpu: 0.38, ram: 0.28, storage: 0.06 },
    req: { gpu: 55, cpu: 68, ramGb: 32, storageTb: 1 },
  },
  graphic_design: {
    name: "그래픽 디자인",
    group: "그래픽",
    w: { gpu: 0.24, cpu: 0.34, ram: 0.32, storage: 0.1 },
    req: { gpu: 35, cpu: 45, ramGb: 16, storageTb: 1 },
  },
  large_canvas_design: {
    name: "대형 캔버스/인쇄 디자인",
    group: "그래픽",
    w: { gpu: 0.24, cpu: 0.3, ram: 0.38, storage: 0.08 },
    req: { gpu: 42, cpu: 55, ramGb: 32, storageTb: 1 },
  },
  modeling_3d: {
    name: "3D 모델링/뷰포트",
    group: "3D 모델링",
    w: { gpu: 0.46, cpu: 0.28, ram: 0.18, storage: 0.08 },
    req: { gpu: 55, cpu: 55, ramGb: 32, storageTb: 1 },
  },
  rendering_3d: {
    name: "3D 렌더링/GPU 렌더",
    group: "3D 모델링",
    w: { gpu: 0.58, cpu: 0.22, ram: 0.16, storage: 0.04 },
    req: { gpu: 74, cpu: 62, ramGb: 32, storageTb: 1 },
  },
  cad_archviz: {
    name: "CAD/건축 시각화",
    group: "3D 모델링",
    w: { gpu: 0.38, cpu: 0.34, ram: 0.22, storage: 0.06 },
    req: { gpu: 55, cpu: 62, ramGb: 32, storageTb: 1 },
  },
  music_prod: {
    name: "음악 제작/DAW",
    group: "음악/개발",
    w: { gpu: 0.04, cpu: 0.58, ram: 0.32, storage: 0.06 },
    req: { gpu: 15, cpu: 60, ramGb: 32, storageTb: 1 },
  },
  coding: {
    name: "코딩/개발",
    group: "음악/개발",
    w: { gpu: 0.05, cpu: 0.52, ram: 0.34, storage: 0.09 },
    req: { gpu: 15, cpu: 55, ramGb: 32, storageTb: 1 },
  },
  ai_dev: {
    name: "AI 개발/로컬 추론",
    group: "AI/개발",
    w: { gpu: 0.62, cpu: 0.18, ram: 0.16, storage: 0.04 },
    req: { gpu: 72, cpu: 55, ramGb: 32, storageTb: 1 },
  },
};
