"""Generate local, disjoint Unicode subsets without dropping original glyphs.

Development-only prerequisites: fonttools[woff]==4.60.2, brotli==1.2.0.
Run after editing UI text to refresh the small common-character subset.
The browser loads other character ranges only when they occur on the page.
"""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/assets/PretendardVariable.woff2"
DESTINATION = ROOT / "src/assets/fonts"


def unicode_ranges(points):
    ranges = []
    for point in sorted(points):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    return ",".join(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
                    for start, end in ranges)


def main():
    with TTFont(SOURCE) as font:
        original = set(font.getBestCmap())
        axes = [(axis.axisTag, axis.minValue, axis.maxValue) for axis in font['fvar'].axes]
    common = set(range(0x20, 0x100))
    for path in (ROOT / "src").rglob("*"):
        if path.suffix in {".js", ".jsx"}:
            common.update(map(ord, path.read_text()))
    common &= original
    remaining = sorted(original - common)
    groups = [("ui", common)] + [
        (f"{offset // 512:02d}", set(remaining[offset:offset + 512]))
        for offset in range(0, len(remaining), 512)
    ]
    DESTINATION.mkdir(parents=True, exist_ok=True)
    css, covered = [], set()
    for name, points in groups:
        filename = f"Pretendard-{name}.woff2"
        options = subset.Options()
        options.flavor = "woff2"
        options.recalc_timestamp = False
        with TTFont(SOURCE, recalcTimestamp=False) as font:
            worker = subset.Subsetter(options=options)
            worker.populate(unicodes=points)
            worker.subset(font)
            font.save(DESTINATION / filename)
        with TTFont(DESTINATION / filename) as result:
            actual = set(result.getBestCmap())
            assert actual == points and not covered.intersection(actual)
            assert [(a.axisTag, a.minValue, a.maxValue) for a in result['fvar'].axes] == axes
            covered.update(actual)
        css.append(f'''@font-face {{
  font-family: Pretendard;
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("./{filename}") format("woff2");
  unicode-range: {unicode_ranges(points)};
}}''')
    assert covered == original
    (DESTINATION / "pretendard.css").write_text(
        "/* Generated by scripts/subset_fonts.py. License: public/fonts/LICENSE.txt. */\n"
        + "\n".join(css) + "\n")
    print(f"Verified {len(original)} characters and all variable weight axes in {len(groups)} subsets.")
    print(f"Initial UI font: {(DESTINATION / 'Pretendard-ui.woff2').stat().st_size:,} bytes; original: {SOURCE.stat().st_size:,} bytes.")


if __name__ == "__main__":
    main()
